baseurl = "https://www.markserena.com.au/"
title = "Mark Serena"
theme = "hugo-nederburg-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
pygmentsUseClassic            = false
pygmentsCodeFences            = true
pygmentsCodeFencesGuessSyntax = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
  slogan = "Technical Artist"
  description = "CG Artist, specializing in 3D; lighting, rendering and anything technical" # meta description
  author = "Mark Serena"
  bio = [
    "Mark is an artist with a passion for technical art and things beyond his comprehension."
  ]
  copyright = [
    "&copy; 2022 Mark Serena"

  ]


  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "mark@markserena.com.au"

  # Nav links in the side bar
  [[menu.main]]
  name = "Blog"
  url = "/"
  weight = 1

    # Nav links in the side bar
  # [[menu.main]]
  # name = "Downloads"
  # url = "downloads/"
  # weight = 2

  [[menu.main]]
  name = "Showreel"
  url = "showreel/"
  weight = 3
  identifier = "Showreel"

# [[menu.main]]
#   weight = 1
#   name   = "Showreel"
#   url    = "showreel/reel"
#   parent = "Portfolio"

# [[menu.main]]
#   weight = 2
#   name   = "Breakdown"
#   url    = "showreel/breakdown/"
#   parent = "Portfolio"

# end submenu


  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 4

  [[menu.main]]
  name = "Contact"
  url = "contact/"
  weight = 5

  # [[menu.main]]
  # name = "Terms"
  # url = "terms/"
  # weight = 6

  [params.social]
  # email       = "mark@markserena.com.au"
  twitter       = "https://twitter.com/_markserena"
  linkedin      = "https://www.linkedin.com/in/markserena/"
  youtube       = "https://www.youtube.com/c/MarkSerena"
  vimeo         = "https://vimeo.com/user19202080"
  github        = "https://github.com/markserena"
  
